### ISSUE TITLE
Compile with gcc 6.1

### ISSUE THREAD

**Issue by gaow** [vatlab/VariantTools#34]
I recently upgraded my gcc to version 6.1 for some bioconductor packages, but now I have an issue with vtools compile:

```
sqlite/vt_sqlite3_ext.cpp: At global scope:
sqlite/vt_sqlite3_ext.cpp:2858:1: error: narrowing conversion of ‘4294967168u’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
 };
 ^
```
Apparently this is some code copied from sqlite and is now obsolete. Maybe there is some upstream changes we should incorporate?

**Comment by gaow** [comment]
Here is with gcc 4.8, its just a warning:

```
sqlite/vt_sqlite3_ext.cpp:2858:1: warning: narrowing conversion of ‘4294965248u’ from ‘unsigned int’ to ‘const int’ inside { } is ill-formed in C++11 [-Wnarrowing]
sqlite/vt_sqlite3_ext.cpp:2858:1: warning: narrowing conversion of ‘4294901760u’ from ‘unsigned int’ to ‘const int’ inside { } is ill-formed in C++11 [-Wnarrowing]
sqlite/vt_sqlite3_ext.cpp: In function ‘int RegisterExtensionFunctions(sqlite3*)’:
```
Maybe we can also ask gcc to always treat this an warning ...

**Comment by BoPeng** [comment]
The [upstream code](https://github.com/seth/RSQLite.extfuns/blob/master/src/extension-functions.c) is not changed as far as I can tell so we will have to fix this by ourselves.

**Comment by BoPeng** [comment]
Do not have your version of gcc here but perhaps you can change `int` to `unsigned int` there?

**Comment by gaow** [comment]
Hmm this seems to have worked though not sure about potential side effects:

```diff
diff --git a/sqlite/vt_sqlite3_ext.cpp b/sqlite/vt_sqlite3_ext.cpp
index 0ad2f55..bfd8e49 100644
--- a/sqlite/vt_sqlite3_ext.cpp
+++ b/sqlite/vt_sqlite3_ext.cpp
@@ -2850,7 +2850,7 @@ static const int xtra_utf8_bits[] = {
 ** masking the character with utf8_mask[N] must produce a non-zero
 ** result.  Otherwise, we have an (illegal) overlong encoding.
 */
-static const int utf_mask[] = {
+static const unsigned int utf_mask[] = {
        0x00000000,
        0xffffff80,
        0xfffff800,
```

Does it make sense to you?

**Comment by gaow** [comment]
Oh sorry I did not see your suggestion ... right we are thinking the same. Should I commit?

**Comment by BoPeng** [comment]
yes, that integer is supposed to be unsigned.
